Resources:
  DemoVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: '10.0.0.0/16'
      Tags:
        - Key: Name
          Value: DemoVPC

    DemoPublicSubnetA:
      Type: 'AWS::EC2::Subnet'
      Properties:
        VpcId: !Ref DemoVPC
        CidrBlock: '10.0.10.0/24'
        AvailabilityZone: ap-southeast-1a
        Tags: 
        - Key: Name
          Value: PublicSubnetA

    DemoPublicSubnetB:
    Type: 'AWS::EC2::Subnet'
    Properties:
    VpcId: !Ref DemoVPC
    CidrBlock: '10.0.1.0/24'
    AvailabilityZone: ap-southeast-1b
    Tags:
    - Key: Name
      Value: PublicSubnetB

    DemoPrivateSubnetA:
    Type: 'AWS::EC2::Subnet'
    Properties:
    VpcId: !Ref DemoVPC
    CidrBlock: '10.0.16.0/20'
    Tags:
    - Key: Name
      Value: PrivateSubnetA